[project]
name = "coding_agent"
version = "0.1.0"
description = "Coding Agent"
requires-python = ">=3.11"

dependencies = [
    "fastapi",
    "uvicorn",
    "websockets",
    "openai",
    "rich",
    "aiofiles",
    "pydantic",
    "mcp",
    "networkx",
    "libcst",
    "jedi",
    "tree_sitter"
]

[dependency-groups]
dev = [
  "pytest",
]

[tool.setuptools]
packages = ["core", "config", "command", "ast_utils", "navigation", "repo_utils", "interfaces", "utils"]
